apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.0.0
    chart: kube-prometheus-stack
    helm:
      # Sets a consistent release name for Helm deployment
      releaseName: prometheus-grafana-monitor 
      valuesObject:
        grafana:
          service:
            type: ClusterIP
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  resources:
                    requests:
                      storage: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # CRITICAL FIX 1: Ensures CRDs are handled correctly and mitigates 
      # the "metadata.annotations: Too long" error by using server-side apply.
      - CreateNamespace=true
      - ServerSideApply=true
      
      # CRITICAL FIX 2: Prevents issues with creating resources before the CRDs are ready.
      - ApplyOutOfSyncOnly=true
      
      # Recommended: Ensures cluster-wide CRDs aren't deleted if this ArgoCD app is removed.
      - PreserveResourcesOnDeletion=true
```eof

**Action:** Replace the content of your `argocd/monitoring-app.yaml` file in your Git repository with the YAML above, commit, and push the changes. ArgoCD will then perform a new sync with these corrected options.
